# Generated by Django 3.2.5 on 2021-09-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
